name: Host

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install obscure libraries
      run: sudo apt-get update && sudo apt-get install libudev-dev libusb-1.0-0-dev
    - name: Build
      run: cd ./host && cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
